name: Build Library

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      artifact_glob:
        type: string
        required: false
        default: "**/*.nupkg"
      artifact_retention_days:
        type: number
        required: false
        default: 1
      nuke_target:
        required: false
        type: string
        default: "CreateNugetPackages"
      configuration:
        required: false
        type: string
        default: "Release"
      runs_on:
        required: false
        type: string
        default: ubuntu-latest
      install_workloads:
        required: false
        type: boolean
        default: true
      dotnet_sdk:
        required: false
        type: string
        default: 9.0.308
    secrets:
      checkout_token:
        required: false

jobs:

  build_library:
    runs-on: ${{ inputs.runs_on }}
    steps:
    - uses: actions/checkout@v4
      with:
          token: ${{ secrets.checkout_token }}
          submodules: 'recursive'

    - uses: actions/setup-dotnet@v4
      with:
          dotnet-version: ${{ inputs.dotnet_sdk }}

    - name: Install Android workload
      if: ${{ inputs.install_workloads && runner.os == 'Linux' }}
      run: dotnet workload install android --version ${{ inputs.dotnet_sdk }}

    - name: Install workloads
      if: ${{ inputs.install_workloads && runner.os != 'Linux' }}
      run: dotnet workload install android ios --version ${{ inputs.dotnet_sdk }}

    - name: Create NuGet Packages
      run: dotnet run --project ${{github.workspace}}/build/_build.csproj -- --target ${{ inputs.nuke_target }} --configuration ${{ inputs.configuration }} --output ${{github.workspace}}/artifacts/packages/

    - name: Upload nupkg artifacts
      uses: actions/upload-artifact@v4
      with:
          name: ${{ inputs.artifact_name }}
          path: ${{github.workspace}}/artifacts/packages/${{ inputs.artifact_glob }}
          retention-days: ${{ inputs.artifact_retention_days }}
