name: Push Package

on:
  workflow_call:
    inputs:
      artifact_name:
        required: true
        type: string
      feed_source:
        required: true
        type: string
    secrets:
      feed_api_key:
        required: true

jobs:

  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v4
      with:
          name: ${{ inputs.artifact_name }}
          path: ./artifacts

    - name: Publish release
      run: dotnet nuget push ./artifacts/**/*.nupkg --api-key ${{secrets.feed_api_key}} --source ${{ inputs.feed_source }}

    - name: Clean packages
      if: always()
      run: rm -rf ./artifacts
