name: Build Library

on:
  workflow_call:
    inputs:
      push_nightly:
        required: false
        type: boolean
        default: false
      push_stable:
        required: false
        type: boolean
        default: false
      nightly_feed:
        required: false
        type: string
        default: "https://nuget-feed-nightly.avaloniaui.net/v3/index.json"
      stable_feed:
        required: false
        type: string
        default: "https://api.nuget.org/v3/index.json"

      artifact_name:
        type: string
        required: false
        default: "nupkg"
      artifact_glob:
        type: string
        required: false
        default: "**/*.nupkg"
      artifact_retention_days:
        type: number
        required: false
        default: 1
      nuke_target:
        required: false
        type: string
        default: "CreateNugetPackages"
      configuration:
        required: false
        type: string
        default: "Release"
      runs_on:
        required: false
        type: string
        default: ubuntu-latest
      install_workloads:
        required: false
        type: boolean
        default: true
      dotnet_sdk:
        required: false
        type: string
        default: 9.0.308
    secrets:
      checkout_token:
        required: true
      nightly_api_key:
        required: false
      stable_api_key:
        required: false

jobs:

  validate-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if push_nightly requires nightly_api_key but is missing
        if: ${{ inputs.push_nightly }} && !${{ secrets.nightly_api_key }}
        run: |
          echo  "push_nightly is true but nightly_api_key is missing."
          exit 1

      - name: Fail if push_stable requires stable_api_key but is missing
        if: ${{ inputs.push_stable }} && !${{ secrets.stable_api_key }}
        run: |
          echo  "push_stable is true but stable_api_key is missing."
          exit 1

      - name: Fail if push_stable is true but ref is not release/*
        if: ${{ inputs.push_stable && !startsWith(github.ref_name, 'release/') }}
        run: |
          echo  "push_stable is true but github.ref_name '${{ github.ref_name }}' is not a release/* branch."
          exit 1

      - name: Validation passed
        run: echo "All validation rules passed."

  build_library:
    runs-on: ${{ inputs.runs_on }}
    steps:
    - uses: actions/checkout@v4
      with:
          token: ${{ secrets.checkout_token }}
          submodules: 'recursive'

    - uses: actions/setup-dotnet@v4
      with:
          dotnet-version: ${{ inputs.dotnet_sdk }}

    - name: Install Android workload
      if: ${{ inputs.install_workloads && runner.os == 'Linux' }}
      run: dotnet workload install android --version ${{ inputs.dotnet_sdk }}

    - name: Install workloads
      if: ${{ inputs.install_workloads && runner.os != 'Linux' }}
      run: dotnet workload install android ios --version ${{ inputs.dotnet_sdk }}

    - name: Create NuGet Packages
      run: dotnet run --project ${{github.workspace}}/build/_build.csproj -- --target ${{ inputs.nuke_target }} --configuration ${{ inputs.configuration }} --output ${{github.workspace}}/artifacts/packages/

    - name: Upload nupkg artifacts
      uses: actions/upload-artifact@v4
      with:
          name: ${{ inputs.artifact_name }}
          path: ${{github.workspace}}/artifacts/packages/${{ inputs.artifact_glob }}
          retention-days: ${{ inputs.artifact_retention_days }}

  publish-nightly-release:
    runs-on: ubuntu-latest
    needs: [build_library]
    if: ${{ inputs.push_nightly }} && (github.event_name == 'push' || github.event_name == 'pull_request') && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    steps:

      - uses: actions/download-artifact@v4
        with:
            name: ${{ inputs.artifact_name }}
            path: ./nupkgs

      - name: Publish Nightly release
        run: dotnet nuget push ./nupkgs/**/*.nupkg --api-key ${{secrets.nightly_api_key}} --source ${{ inputs.nightly_feed }}

  publish-stable-release:
    runs-on: ubuntu-latest
    needs: [build_library]
    if: ${{ inputs.push_stable }}
    steps:

    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ./nupkgs

    - name: Publish Stable release
      run: dotnet nuget push ./nupkgs/**/*.nupkg --api-key ${{secrets.stable_api_key}} --source ${{ inputs.stable_feed }}
