<Project>
    <!--
      Nullable annotations are incomplete for netstandard2.0. By default, this file suppresses
      nullable warnings for targets before .NET 6. It treats the warnings as errors for newer targets.

      Set SuppressNullableWarnings=false to enable warnings for targets before .NET 6.
      Set DisableNullableErrors=true to keep the warnings for newer targets as warnings.
    -->
    <PropertyGroup Condition="'$(Nullable)' == ''">
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <PropertyGroup Condition="'$(DisableNullableErrors)' != 'true'">
        <WarningsAsErrors Condition="$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">$(WarningsAsErrors);nullable</WarningsAsErrors>
    </PropertyGroup>
    <PropertyGroup Condition="'$(SuppressNullableWarnings)' != 'false'">
        <NoWarn Condition="!$([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net6.0'))">$(NoWarn);nullable</NoWarn>
    </PropertyGroup>
</Project>
